FROM apache/spark:3.5.1

USER root

# Python 패키지
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Jupyter
RUN pip install jupyterlab

WORKDIR /workspace

EXPOSE 8888 4040